In [12]:
import numpy as np

In [32]:
#One Dimensional Array

In [2]:
one_dimension_array = np.array([1, 2, 3, 4, 5, 6])

In [3]:
one_dimension_array

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Two Dimensional Array

In [4]:
two_dimension_array = np.array([[1,2],[3,4]])

In [5]:
two_dimension_array

array([[1, 2],
       [3, 4]])

In [33]:
#Three Dimensional Array

In [ ]:
three_dimension_array = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

In [ ]:
three_dimension_array

In [34]:
#Basic Maths Operations

In [ ]:


# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])




In [ ]:
# Element-wise addition
result_add = arr1 + arr2

# Element-wise multiplication
result_multiply = arr1 * arr2



In [ ]:
print("Addition:", result_add)
print("Multiplication:", result_multiply)

In [ ]:


# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])




In [ ]:
# Element-wise addition
result_add = arr1 + arr2

# Element-wise multiplication
result_multiply = arr1 * arr2



In [ ]:
print("Addition:", result_add)
print("Multiplication:", result_multiply)

In [35]:
#Mathematical Functions Operations:
arr = np.array([1, 2, 3, 4])



In [60]:
#Sum of all the elements of an array
arr.sum()

10

In [61]:
#Sum of a row of elements of an array
sum(arr)

10

In [62]:
#Standard Deviation of the array
arr.std()

1.118033988749895

In [36]:
# Element-wise square root
result_sqrt = np.sqrt(arr)



In [ ]:
# Element-wise exponential
result_exp = np.exp(arr)

print("Square root:", result_sqrt)
print("Exponential:", result_exp)

In [37]:
#Logical Operations

In [38]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, True, True, False])


In [39]:
# Element-wise logical AND
result_and = np.logical_and(arr1, arr2)

# Element-wise logical OR
result_or = np.logical_or(arr1, arr2)

In [40]:
print("Logical AND:", result_and)
print("Logical OR:", result_or)

Logical AND: [False False  True False]
Logical OR: [ True  True  True False]


In [ ]:
#Numpy Ones

In [ ]:
one_np =np.ones(5)
one_np

In [ ]:
five_np = one_np * 5
five_np

In [42]:
#Numpy Identity Matrix

In [43]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
#Numpy Broadcasting

In [ ]:
# Create a 2D array (3x3)
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Create a 1D array (3 elements)
arr2 = np.array([10, 20, 30])

# Perform element-wise addition between a 2D and a 1D array
result = arr1 + arr2

print("Array 1 (2D):\n", arr1)
print("Array 2 (1D):\n", arr2)
print("Result (Broadcasted Addition):\n", result)

In [45]:
a = np.array([1.0, 2.0, 3.0])

b = np.array([2.0, 2.0, 2.0])

a * b


array([2., 4., 6.])

In [46]:
#Numpy Reshaping

In [47]:
matrix = np.arange(1,26)
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [48]:
matrix_reshape = matrix.reshape(5,5)
matrix_reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
#Numpy Slicing

In [50]:
matrix = np.arange(1,26).reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
matrix[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [53]:
matrix[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [55]:
matrix[4,:]

array([21, 22, 23, 24, 25])

In [56]:
matrix[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#